---
title: "EDA VIS canções"
subtitle: 'Análise sobre Jackson do Pandeiro'
author: "José Benardi de Souza Nunes"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---

```{r}
library(tidyverse)
library(dplyr, warn.conflicts = FALSE)
library(here)
library(plotly)
library(highcharter)
library(stringr)
theme_set(theme_bw())
```

## Data Overview

```{r}
data <- read_csv(here::here("data/jackson.csv"), 
                            col_types = cols(
                                .default = col_double(),
                                album_uri = col_character(),
                                album_name = col_character(),
                                album_img = col_character(),
                                album_release_date = col_character(),
                                album_release_year = col_date(format = ""),
                                album_popularity = col_integer(),
                                track_name = col_character(),
                                track_uri = col_character(),
                                key = col_character(),
                                mode = col_character(),
                                time_signature = col_integer(),
                                key_mode = col_character(),
                                track_popularity = col_integer()
                                )) %>%
         mutate(album_name = gsub(".*(1954).*",
                                         "The Music of Brazil/Jackson do Pandeiro",
                                  album_name));
data %>% 
    glimpse()
```

### Danceability

```{r}
data %>% 
    ggplot(aes(sample=danceability)) + 
        stat_qq()
```

```{r}
hchart (data$danceability,
        color = "#B71C1C",
        name = "Dançabilidade")
```


### Speechines

```{r}
data %>% 
    ggplot(aes(sample=speechiness)) + 
        stat_qq()
```

```{r}
hchart (data$speechiness,
        color = "#B71C1C",
        name = "Verbosidade")
```

### Duration

```{r}
data <- data %>%
    mutate(duration_s = duration_ms/1000)

data %>% 
    select(duration_s) %>%
    glimpse()
```


```{r}
data %>% 
    ggplot(aes(sample=duration_s)) + 
        stat_qq()
```

```{r}
hchart (data$duration_s,
        color = "#B71C1C",
        name = "Duração (s)")
```

### Remaster

Ultimo album "1981: Isso é que é Forró!"

```{r}
data <- data %>%
    mutate(remaster = album_release_date > "1981-30-12")

data %>% 
    select(album_name, album_release_year, remaster) %>%
    sample_n(10)
```


```{r}
temp <- data %>% 
    distinct(album_name,
             .keep_all = TRUE) %>%
    mutate(remaster = ifelse(remaster == TRUE,"remasterizado","original"))

hchart(temp$remaster,
       colorByPoint = TRUE,
       name="Álbum")
```



## Mais discurso/diálogo (speechines) tem efeito sobre a dançabilidade da música?

```{r}
p <- data %>% 
        distinct(track_name, .keep_all = TRUE) %>%
        ggplot(aes(x=speechiness,
                   y=danceability)) +
        geom_point(alpha=0.4) 

ggplotly(p)
```

```{r}
data %>% 
    distinct(track_name, .keep_all = TRUE) %>%
    ggplot(aes(speechiness,danceability)) +
    stat_density2d(aes(fill = ..level..), geom = "polygon")
```

```{r}
data %>%
    group_by(track_name) %>%
    top_n(10, speechiness)
```

## Como o passar dos anos afeta o tempo de duração da música?

```{r}
data %>% 
    distinct(album_name, .keep_all = TRUE) %>%
    ggplot(aes(as.factor(album_release_year),
               group=album_release_year,
               fill=remaster)) +
    geom_bar() +
    theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r}
hchart(temp$album_release_date,
       name="Número de albuns")
```

```{r}
data %>% 
    ggplot(aes(x=as.factor(album_release_year),
               duration_s,
               group=album_release_year,
               color=remaster)) +
    geom_boxplot(position = "dodge", alpha=0.6) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1))

```

## Os albuns relançados/remasterizados são mais populares? 

```{r}
# lollipop chart
m <- list(
  l = 370)

p <- data %>%
        ggplot(aes(album_popularity,y=reorder(album_name,album_popularity),
                   color=remaster,
                   group=remaster)) +
            geom_segment(aes(x = 0, y = reorder(album_name,album_popularity), 
                             xend = album_popularity, 
                             yend = album_name)) + 
        geom_point() +
        theme(axis.title.y=element_blank())

ggplotly(p) %>%
  layout(autosize = F,
         margin = m)
```

